In [8]:
import numpy as np
import sys
sys.path.append('../src')
from paths import ROOTPATH
import json



In [21]:
output_json = json.load(open(ROOTPATH+'data/lorenzww.json'))
data = {
'time': [np.array(time) for time in output_json['times']],
'dt': output_json['times'][0][1]-output_json['times'][0][0],
'x': [np.array(x) for x in output_json['omegas']],
'dx': [np.array(x) for x in output_json['domegas']],
}

In [24]:
data

{'time': [array([0.00000000e+00, 4.17083333e-02, 8.34166667e-02, ...,
         1.08316542e+02, 1.08358250e+02, 1.08399958e+02]),
  array([108.44166667, 108.483375  , 108.52508333, ..., 216.75820833,
         216.79991667, 216.841625  ]),
  array([216.88333333, 216.92504167, 216.96675   , ..., 325.199875  ,
         325.24158333, 325.28329167]),
  array([325.325     , 325.36670833, 325.40841667, ..., 433.64154167,
         433.68325   , 433.72495833]),
  array([453.78666667, 453.828375  , 453.87008333, 453.91179167,
         453.9535    , 453.99520833, 454.03691667, 454.078625  ,
         454.12033333, 454.16204167, 454.20375   , 454.24545833,
         454.28716667, 454.328875  , 454.37058333, 454.41229167,
         454.454     , 454.49570833, 454.53741667, 454.579125  ,
         454.62083333, 454.66254167, 454.70425   , 454.74595833,
         454.78766667, 454.829375  , 454.87108333, 454.91279167,
         454.9545    , 454.99620833, 455.03791667, 455.079625  ,
         455.12133333, 4